name: Build NAPI-RS
on:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false
jobs:
  # ---------------------------------------------------------------------------- #
  build-napi-rs-x86_64-apple-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - uses: jcbhmr/setup-rust-action@7b33a1b8513dbb33845400d19f16a9bd290d54df
        with:
          target: x86_64-apple-darwin
      - run: npm ci
      - if: inputs.release
        run: npx napi build --platform --release --target x86_64-apple-darwin
      - if: "!inputs.release"
        run: npx napi build --platform --target x86_64-apple-darwin
      - uses: actions/upload-artifact@v3
        with:
          name: x86_64-apple-darwin
          path: index.darwin-x64.node
          if-no-files-found: error
  # ---------------------------------------------------------------------------- #
  build-napi-rs-x86_64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    container: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - uses: jcbhmr/setup-rust-action@7b33a1b8513dbb33845400d19f16a9bd290d54df
        with:
          target: x86_64-unknown-linux-gnu
      - run: sudo apt-get update && sudo apt-get install libgtk-3-dev
      - run: npm ci
      - if: inputs.release
        run: npx napi build --platform --release --target x86_64-unknown-linux-gnu
      - if: "!inputs.release"
        run: npx napi build --platform --target x86_64-unknown-linux-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: x86_64-unknown-linux-gnu
          path: index.linux-x64-gnu.node
          if-no-files-found: error
  # ---------------------------------------------------------------------------- #
  build-napi-rs-x86_64-pc-windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - uses: jcbhmr/setup-rust-action@7b33a1b8513dbb33845400d19f16a9bd290d54df
        with:
          target: x86_64-pc-windows-msvc
      - run: npm ci
      - if: inputs.release
        run: npx napi build --platform --release --target x86_64-pc-windows-msvc
      - if: "!inputs.release"
        run: npx napi build --platform --target x86_64-pc-windows-msvc
      - uses: actions/upload-artifact@v3
        with:
          name: x86_64-pc-windows-msvc
          path: index.win32-x64-msvc.node
          if-no-files-found: error
# ---------------------------------------------------------------------------- #
