name: Deploy GH Pages
on:
  release:
    types: published
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  deploy-gh-pages:
    permissions:
      contents: read
      pages: write
      deployments: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: rustup toolchain install stable
      - run: sudo apt-get update && sudo apt-get install libgtk-3-dev
      - run: npm ci
      - id: configure-pages
        uses: actions/configure-pages@v3
      - run: npm run build:docs
        env:
          BASE_URL: ${{ steps.configure-pages.outputs.base_url }}/
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/dist
      - id: deploy-pages
        uses: actions/deploy-pages@v2
