name: Test
on:
  push:
    branches: "main"
    paths-ignore:
      - docs/**
      - .github/**
      - "!.github/workflows/test.yml"
      - .gitignore
      - LICENSE
      - README.md
  pull_request:
    paths-ignore:
      - docs/**
      - .github/**
      - "!.github/workflows/test.yml"
      - .gitignore
      - LICENSE
      - README.md
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  test-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            npm ci
            npm pack --dry-run
      - uses: actions/upload-artifact@v3
        with:
          name: node-addon
          path: |
            index*.node
            index.js
            index.d.ts
  test-nodejs:
    needs: test-rust
    strategy:
      matrix:
        node-version: ["16", "18", "20"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: hecrj/setup-rust-action@v1
        with:
          components: cargo-fmt
        # https://github.com/hecrj/setup-rust-action/issues/32
        continue-on-error: true
      - if: runner.os == 'Linux'
        run: export DEBIAN_FRONTEND=noninteractive && sudo apt-get update -y && sudo apt-get install -y --no-install-recommends libglib2.0-dev libatk1.0-dev libgtk-3-dev && sudo rm -rf /var/lib/apt/lists/*
      - if: runner.os == 'macOS'
        uses: goto-bus-stop/setup-zig@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - uses: actions/download-artifact@v3
        with:
          name: node-addon
      - run: npm test
  # test-deno:
  # test-bun:
